services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: juraganapartemen_app
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    env_file:
      - .env

  vite:
    image: node:20
    working_dir: /var/www/html
    container_name: juraganapartemen_vite
    volumes:
      - .:/var/www/html
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"

  web:
    image: nginx:alpine
    container_name: juraganapartemen_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - vite

  db:
    image: mysql:8.0
    container_name: juraganapartemen_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: juraganapartemen_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

volumes:
  db_data:
